name: 'DigitalOcean Spaces Action'
description: 'Upload files to DigitalOcean Spaces (Even with Metadata <3)'
inputs:
  key:
    description: 'Spaces api key'
    required: true
  secret:
    description: 'Spaces api secret'
    required: true
  region:
    description: 'Spaces region e.g. sfo3'
    required: true
  bucket:
    description: 'Spaces bucket name'
    required: true
  src:
    description: 'Source file or directory (soon)'
    required: true
  dest:
    description: 'Destination path'
    required: true
  private:
    description: 'Specify file visibility (public or private)'
    required: true
  metadata:
    description: 'Specify file metadata (e.g. Git-Hash: 123456789) [Optional]'
    required: false
outputs:
  result:
    description: 'Endpoint Result URL'
runs:
  using: 'node16'
  main: 'dist/index.js'
